### PR TITLE
Remove echo#14

### LINKED ISSUE #14: Remove echo

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #14.

So you don't get spammed

### CODE REVIEW

**Comment by LowWeiLin** [comment]
I think you should create an issue first. But we don't have a guide for contributors so watever.

**Comment by kanghj** [comment]
Changes made @LowWeiLin

**Comment by LowWeiLin** [comment]
@dariusf please decide the fate of this PR, since you are already working on it.

**Comment by dariusf** [comment]
I'm working on generalising the config (getting it from a `.hubturbot` file from the repo). First commit is fine though, don't need it to test any more :+1:

**Pull request merged**
